"""Generate ROADMAP.md, graph.dot and graph.svg from the canonical roadmap.json.

Nothing here is ever hand-edited. `md_is_stale` re-renders and compares, so both a
changed roadmap.json *and* a hand-edited ROADMAP.md register as drift.
Stdlib only; the SVG step shells out to graphviz `dot` and degrades quietly.
"""
from __future__ import annotations

import os
import re
import subprocess

from .graph import (
    TIER_RANK,
    blocked_items,
    blockers,
    next_items,
    score_of,
)
from .schema import KINDS, STATUSES, content_hash, load, paths_for

BANNER_PREFIX = "<!-- generated by roadmap.py render — source: "
_HASH_RE = re.compile(r"sha256:([0-9a-f]{64})")

STATUS_COLOR = {
    "proposed": "#e8e8e8",
    "ready": "#cfe8ff",
    "in-progress": "#ffe8a3",
    "done": "#b7e1cd",
    "dropped": "#f0d0d0",
}
BLOCKED_OUTLINE = "#c0392b"


def _esc(text):
    """Escape a string for a quoted graphviz label."""
    out = str(text or "").replace("\\", "\\\\").replace('"', '\\"')
    return out.replace("\r", " ").replace("\n", "\\n")


def _node_id(item_id):
    return str(item_id).replace("-", "_")


# ------------------------------------------------------------------------- dot

def _node_line(doc, item, indent="  "):
    label = "%s · %s\\n%s · %s" % (
        _esc(item.get("id")),
        _esc(item.get("title")),
        _esc(item.get("kind")),
        _esc(item.get("status")),
    )
    fill = STATUS_COLOR.get(item.get("status"), "#e8e8e8")
    extra = ""
    if item.get("status") not in ("done", "dropped") and blockers(doc, item):
        extra = ', color="%s", penwidth=2' % BLOCKED_OUTLINE
    return '%s"%s" [label="%s", fillcolor="%s"%s];' % (
        indent, _esc(item.get("id")), label, fill, extra,
    )


def render_dot(doc):
    items = doc.get("items", [])
    by_id = {i.get("id"): i for i in items}

    children = {}
    for item in items:
        parent = item.get("parent")
        if parent and parent in by_id:
            children.setdefault(parent, []).append(item)

    lines = [
        "digraph roadmap {",
        "  rankdir=LR;",
        '  graph [fontname="Helvetica", fontsize=11];',
        '  node [shape=box, style="filled,rounded", fontname="Helvetica", fontsize=10];',
        '  edge [color="#666666"];',
        "",
    ]

    emitted = set()
    for parent_id in sorted(children):
        parent = by_id[parent_id]
        lines.append("  subgraph cluster_%s {" % _node_id(parent_id))
        lines.append('    label="%s";' % _esc(parent.get("title")))
        lines.append('    style="rounded,dashed";')
        lines.append('    color="#aaaaaa";')
        group = [parent] + sorted(children[parent_id], key=lambda i: i.get("id", ""))
        for item in group:
            if item.get("id") not in emitted:
                lines.append(_node_line(doc, item, indent="    "))
                emitted.add(item.get("id"))
        lines.append("  }")

    for item in sorted(items, key=lambda i: i.get("id", "")):
        if item.get("id") not in emitted:
            lines.append(_node_line(doc, item))
            emitted.add(item.get("id"))

    lines.append("")
    for item in sorted(items, key=lambda i: i.get("id", "")):
        for dep in sorted(set(item.get("deps") or [])):
            if dep in by_id:
                lines.append('  "%s" -> "%s";' % (_esc(dep), _esc(item.get("id"))))
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_svg(dot_path, svg_path, dot_binary="dot"):
    """Render the SVG. Returns the path, or None when graphviz is unavailable."""
    try:
        subprocess.run(
            [dot_binary, "-Tsvg", dot_path, "-o", svg_path],
            check=True, capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return svg_path


# -------------------------------------------------------------------- markdown

def _score_cell(item):
    score = score_of(item)
    if score is None:
        return "—"
    method = (item.get("priority") or {}).get("method") or "score"
    return "%s %.2f" % (method, score)


def _links_cell(item):
    links = item.get("links") or {}
    parts = []
    if links.get("prd"):
        parts.append("PRD %s" % links["prd"])
    if links.get("plan"):
        parts.append("[plan](%s)" % links["plan"])
    if links.get("adr"):
        parts.append("ADR %s" % links["adr"])
    for issue in links.get("issues") or []:
        parts.append(str(issue))
    return ", ".join(parts) if parts else "—"


def _row(cells):
    return "| " + " | ".join(cells) + " |"


def render_md(doc, rel_svg, rel_json="docs/roadmap/roadmap.json"):
    items = doc.get("items", [])
    digest = content_hash(doc)
    lines = [
        "%s%s sha256:%s — do not edit by hand -->" % (BANNER_PREFIX, rel_json, digest),
        "",
        "# Roadmap — %s" % doc.get("scope", "unscoped"),
        "",
        "Living inventory of every feature, page, function, integration and "
        "operational need. Generated from `%s`; regenerate with `/roadmap render`." % rel_json,
        "",
    ]

    by_status = {s: 0 for s in STATUSES}
    for item in items:
        if item.get("status") in by_status:
            by_status[item["status"]] += 1
    counts = " · ".join("%s %d" % (s, by_status[s]) for s in STATUSES)
    lines += [
        "**%d items** — %s" % (len(items), counts),
        "",
        "Last updated %s · last reconciled %s"
        % (doc.get("updated", "—"), doc.get("last_reconcile") or "never"),
        "",
    ]

    upcoming = next_items(doc)
    lines += ["## Next up (unblocked)", ""]
    if upcoming:
        lines += [
            _row(["ID", "Kind", "Title", "Tier", "Priority", "Links"]),
            _row(["---"] * 6),
        ]
        for item in upcoming:
            lines.append(_row([
                item.get("id", ""),
                item.get("kind", ""),
                item.get("title", ""),
                item.get("tier", ""),
                _score_cell(item),
                _links_cell(item),
            ]))
    else:
        lines.append("_Nothing unblocked. Finish an in-progress item or resolve a blocker._")
    lines.append("")

    waiting = blocked_items(doc)
    if waiting:
        lines += ["## Blocked", "", _row(["ID", "Title", "Blocked by"]), _row(["---"] * 3)]
        for item in waiting:
            lines.append(_row([
                item.get("id", ""),
                item.get("title", ""),
                ", ".join(blockers(doc, item)) or "—",
            ]))
        lines.append("")

    lines += ["## Dependency graph", "", "![roadmap graph](%s)" % rel_svg, ""]

    lines += ["## All items by tier", ""]
    for tier in sorted(TIER_RANK, key=lambda t: TIER_RANK[t]):
        tier_items = sorted(
            (i for i in items if i.get("tier") == tier),
            key=lambda i: i.get("id", ""),
        )
        if not tier_items:
            continue
        lines += [
            "### %s (%d)" % (tier, len(tier_items)),
            "",
            _row(["ID", "Kind", "Status", "Title", "Deps", "Phase"]),
            _row(["---"] * 6),
        ]
        for item in tier_items:
            lines.append(_row([
                item.get("id", ""),
                item.get("kind", ""),
                item.get("status", ""),
                item.get("title", ""),
                ", ".join(item.get("deps") or []) or "—",
                item.get("phase") or "—",
            ]))
        lines.append("")

    by_kind = {}
    for item in items:
        by_kind.setdefault(item.get("kind"), []).append(item)
    if by_kind:
        lines += ["## Coverage by kind", "", _row(["Kind", "Total", "Done"]), _row(["---"] * 3)]
        for kind in KINDS:
            group = by_kind.get(kind)
            if not group:
                continue
            done = sum(1 for i in group if i.get("status") == "done")
            lines.append(_row([kind, str(len(group)), str(done)]))
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def md_hash(markdown):
    """The source hash recorded in a rendered ROADMAP.md banner, or None."""
    first = markdown.splitlines()[0] if markdown else ""
    match = _HASH_RE.search(first)
    return match.group(1) if match else None


# ------------------------------------------------------------------ orchestration

def _rel(target, start_dir):
    return os.path.relpath(target, start_dir).replace(os.sep, "/")


def expected_md(doc, json_path):
    paths = paths_for(json_path)
    md_dir = os.path.dirname(paths["md"])
    return render_md(doc, _rel(paths["svg"], md_dir), _rel(paths["json"], md_dir))


def md_is_stale(json_path):
    """True when ROADMAP.md is missing, out of date, or hand-edited."""
    paths = paths_for(json_path)
    if not os.path.exists(paths["md"]):
        return True
    doc = load(json_path)
    with open(paths["md"], encoding="utf-8") as fh:
        current = fh.read()
    return current != expected_md(doc, json_path)


def render_all(json_path, dot_binary="dot"):
    """Write graph.dot, graph.svg (best effort) and ROADMAP.md."""
    doc = load(json_path)
    paths = paths_for(json_path)
    os.makedirs(paths["graph_dir"], exist_ok=True)

    with open(paths["dot"], "w", encoding="utf-8") as fh:
        fh.write(render_dot(doc))

    svg = write_svg(paths["dot"], paths["svg"], dot_binary=dot_binary)

    os.makedirs(os.path.dirname(paths["md"]), exist_ok=True)
    with open(paths["md"], "w", encoding="utf-8") as fh:
        fh.write(expected_md(doc, json_path))

    return {"json": paths["json"], "dot": paths["dot"], "svg": svg, "md": paths["md"]}
